package com.xioq.dasacumen.model.systemadmin;

// Generated 06-May-2014 10:03:55 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Immutable;
import org.hibernate.annotations.Proxy;

import com.xioq.dasacumen.lib.model.ModelBase;
import com.xioq.dasacumen.model.constants.EntityType;

/**
 * UserDataCat generated by hbm2java
 */
@Entity
@Proxy(lazy=false) 
@Immutable
@Cache(usage=CacheConcurrencyStrategy.READ_ONLY, region="userDataTypesCache")
@Table(name = "user_data_cat")
public class UserDataCat extends ModelBase implements java.io.Serializable {

	@Id
	private Long id;
	
	@JsonIgnore
	@ManyToOne @JoinColumn(name="user_data_cat_parent_id", nullable=true)
	private UserDataCat parentCat;
	
	@Column(name="name")
	private String name;
	
	@Column(name="description")
	private String description;
	
	@Column(name="language_code")
	private String languageCode;
	
	@Column(name="desc_code")
	private String descCode;
	
	@OneToMany(fetch=FetchType.EAGER)
    @JoinColumn(name="user_data_cat_parent_id")
	private Set<UserDataCat> childCategories = new HashSet<UserDataCat>(0);
	
	@OneToMany(fetch=FetchType.EAGER)
    @JoinColumn(name="user_data_cat_id")
	private Set<UserDataTypes> userDataTypes = new HashSet<UserDataTypes>(0);

	public UserDataCat() {
	}

	public UserDataCat(Long id) {
		this.id = id;
	}

	public UserDataCat(Long id, String name, String description,
			String languageCode, String descCode,
			Set<UserDataTypes> userDataTypeses, 
			Set<UserDataCat> userDataCats) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.languageCode = languageCode;
		this.descCode = descCode;
		this.userDataTypes = userDataTypeses;
		this.childCategories = userDataCats;
	}
	
	@Override
	public EntityType getModelType()
	{
		return EntityType.USER_DATA_CAT;
	}

	public Long getId() {
		return this.id;
	}

	private void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getLanguageCode() {
		return this.languageCode;
	}

	public void setLanguageCode(String languageCode) {
		this.languageCode = languageCode;
	}

	public String getDescCode() {
		return this.descCode;
	}

	public void setDescCode(String descCode) {
		this.descCode = descCode;
	}

	public Set<UserDataTypes> getUserDataTypes() {
		return this.userDataTypes;
	}

	public void setUserDataTypes(Set<UserDataTypes> userDataTypes) {
		this.userDataTypes = userDataTypes;
	}

	public UserDataCat getParentCat()
	{
		return parentCat;
	}

	public void setParentCat(UserDataCat parentCat)
	{
		this.parentCat = parentCat;
	}

	public Set<UserDataCat> getChildCategories()
	{
		return childCategories;
	}

	public void setChildCategories(Set<UserDataCat> childCategories)
	{
		this.childCategories = childCategories;
	}

}