package com.xioq.dasacumen.model.common;

// Generated 24-Jun-2014 12:24:54 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;

import com.xioq.dasacumen.lib.model.VersionControlled;
import com.xioq.dasacumen.model.constants.EntityType;

/**
 * BankDetails generated by hbm2java
 */

@Entity @Proxy(lazy=false)
@Table(name = "bank_details")
public class BankDetail extends VersionControlled implements java.io.Serializable {
	
	@Id
	@SequenceGenerator(allocationSize=1, sequenceName="bank_details_id_seq", name="bank_details_id_seq")
	@GeneratedValue(generator="bank_details_id_seq", strategy=GenerationType.SEQUENCE)
	private Long id;

	private String bankName;
	private String bankAddress;
	private String accountNumber;
	private String sortCode;

	@OneToMany(mappedBy="bankDetails")
	private Set<PartyBankDetail> partyBankDetails = new HashSet<PartyBankDetail>(0);

	public BankDetail() {
	}

	public BankDetail(Long id) {
		this.id = id;
	}

	public BankDetail(Long id, String bankName, String bankAddress, String accountNumber, String sortCode, Integer tenantId, String createdBy,
			Date createdDate, String lastUpdatedBy, Date lastUpdatedDate, Integer versionNumber, Set<PartyBankDetail> partyBankDetails) {
		this.id = id;
		this.bankName = bankName;
		this.bankAddress = bankAddress;
		this.accountNumber = accountNumber;
		this.sortCode = sortCode;
		this.partyBankDetails = partyBankDetails;
	}

	@Override
	public EntityType getModelType() {
		return EntityType.BANK_DETAILS;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public String getBankAddress() {
		return this.bankAddress;
	}

	public void setBankAddress(String bankAddress) {
		this.bankAddress = bankAddress;
	}

	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	public String getSortCode() {
		return this.sortCode;
	}

	public void setSortCode(String sortCode) {
		this.sortCode = sortCode;
	}

	public Set<PartyBankDetail> getPartyBankDetails() {
		return this.partyBankDetails;
	}

	public void setPartyBankDetails(Set<PartyBankDetail> partyBankDetails) {
		this.partyBankDetails = partyBankDetails;
	}

}
