package com.xioq.dasacumen.model.common;

import javax.persistence.Entity;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Proxy;

import com.xioq.dasacumen.model.constants.EntityType;

// Generated 06-May-2014 10:03:55 by Hibernate Tools 4.0.0


/**
 * Companies generated by hbm2java
 * TODO 
 */
@PrimaryKeyJoinColumn(name="parties_id")
@Entity @Proxy(lazy=false)
@Table(name="companies")
public class Company  extends Party implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String name;
	private String regNo;
	private String vatNo;
	
	@Transient //XXX I am unsure where this is being populated
	private Address mainAddress;
	
	public Company() {
	}

	public Company(Long id) {
		super(id);
	}

	public Company(Long id, String name, String regNo,
			String vatNo) {
		this(id);
		this.name = name;
		this.regNo = regNo;
		this.vatNo = vatNo;
	}
	
	@Override
	public EntityType getModelType()
	{
		return EntityType.COMPANIES;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getRegNo() {
		return this.regNo;
	}

	public void setRegNo(String regNo) {
		this.regNo = regNo;
	}

	public String getVatNo() {
		return this.vatNo;
	}

	public void setVatNo(String vatNo) {
		this.vatNo = vatNo;
	}

	public Address getMainAddress() {
		if (this.mainAddress == null)
			mainAddress = new Address();
		
		return mainAddress;
	}

	public void setMainAddress(Address mainAddress) {
		this.mainAddress = mainAddress;
	}	
}
