package com.xioq.dasacumen.model.common;

import javax.persistence.Entity;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;

import com.xioq.dasacumen.model.constants.EntityType;

// Generated 24-Jun-2014 12:24:54 by Hibernate Tools 4.0.0


/**
 * InternalResources generated by hbm2java
 */
@PrimaryKeyJoinColumn(name="parties_id")
@Entity @Proxy(lazy=false)
@Table(name="internal_resources")
public class InternalResource extends Party implements java.io.Serializable  {

	private String position;
	private String reportTo;
	private String forenames;
	private String surname;
	private String gender;

	public InternalResource() {
	}

	public InternalResource(Long id, String reportTo, String position,
			String forenames, String surname, String gender) {
		super(id);
		this.position = position;
		this.reportTo = reportTo;
		this.forenames = forenames;
		this.surname = surname;
		this.gender = gender;

	}
	
	@Override
	public EntityType getModelType()
	{
		return EntityType.INTERNAL_RESOURCE;
	}

	public String getReportTo() {
		return this.reportTo;
	}

	public void setReportTo(String reportTo) {
		this.reportTo = reportTo;
	}

	public String getForenames() {
		return this.forenames;
	}
	
	public String getName()
	{
		String tmp = getForenames();
		if(null != tmp && !tmp.isEmpty())
			tmp += " ";
		else
			tmp = "";
		tmp += getSurname();
		return tmp;
	}

	public void setForenames(String forenames) {
		this.forenames = forenames;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	/**
	 * @return the position
	 */
	public String getPosition() {
		return position;
	}

	/**
	 * @param position the position to set
	 */
	public void setPosition(String position) {
		this.position = position;
	}

}
