package com.xioq.dasacumen.model.common;

// Generated 24-Jun-2014 12:24:54 by Hibernate Tools 4.0.0

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.xioq.dasacumen.lib.model.VersionControlled;
import com.xioq.dasacumen.model.constants.EntityType;

/**
 * OtherDetails generated by hbm2java
 */
@Entity()
@Table(name="other_details")
public class OtherDetail extends VersionControlled implements java.io.Serializable {

	@Id
	@SequenceGenerator(allocationSize=1, sequenceName="other_details_id_seq", name="other_details_id_seq")
	@GeneratedValue(generator="other_details_id_seq", strategy=GenerationType.SEQUENCE)
	private Long id;
	
	@ManyToOne
	@JoinColumn(name="parties_id", nullable=false)
	private Party party;
	
	private String field;

	private String value;

	public OtherDetail() {
	}

	public OtherDetail(Long id, Party party) {
		this.id = id;
		this.party = party;
	}

	public OtherDetail(Long id, Party party, String field, String value) {
		this.id = id;
		this.party = party;
		this.field = field;
		this.value = value;
	}

	@Override
	public EntityType getModelType()
	{
		return EntityType.OTHER_DETAILS;
	}
	
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Party getParty() {
		return this.party;
	}

	public void setParty(Party party) {
		this.party = party;
	}

	public String getField() {
		return this.field;
	}

	public void setField(String field) {
		this.field = field;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}
}
