package com.xioq.dasacumen.model.common;

// Generated 24-Jun-2014 12:24:54 by Hibernate Tools 4.0.0

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.xioq.dasacumen.lib.model.VersionControlled;
import com.xioq.dasacumen.model.constants.EntityType;

/**
 * PartyType generated by hbm2java
 */
@Entity
@Table(name="party_type")
public class PartyType extends VersionControlled implements java.io.Serializable {

	@Id
	@SequenceGenerator(allocationSize=1, sequenceName="party_type_id_seq", name="party_type_id_seq")
	@GeneratedValue(generator="party_type_id_seq", strategy=GenerationType.SEQUENCE)
	private Long id;
	
	@ManyToOne
	@JoinColumn(name="parties_id", nullable=false)
	private Party party;
	
	private String typeName;

	public PartyType() {
	}

	public PartyType(Long id, Party party) {
		this.id = id;
		this.party = party;
	}

	public PartyType(Long id, Party party, String typeName) {
		this.id = id;
		this.party = party;
		this.typeName = typeName;;
	}

	@Override
	public EntityType getModelType()
	{
		return EntityType.PARTY_TYPE;
	}
	
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Party getParty() {
		return this.party;
	}

	public void setParty(Party party) {
		this.party = party;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}
}
