package com.xioq.dasacumen.model.common;

// Generated 24-Jun-2014 12:24:54 by Hibernate Tools 4.0.0

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnore;

import com.xioq.dasacumen.lib.model.VersionControlled;
import com.xioq.dasacumen.model.constants.EntityType;

/**
 * PartyBankDetails generated by hbm2java
 */
@Entity
@Table(name="party_bank_details")
public class PartyBankDetail extends VersionControlled implements java.io.Serializable, Comparable<PartyBankDetail> {

	@Id
	@SequenceGenerator(allocationSize=1, sequenceName="party_bank_details_id_seq", name="party_bank_details_id_seq")
	@GeneratedValue(generator="party_bank_details_id_seq", strategy=GenerationType.SEQUENCE)
	private Long id;
	
	@ManyToOne(cascade =CascadeType.ALL)
	@JoinColumn(name="bank_details_id", nullable=false)
	private BankDetail bankDetails;
	
	@JsonIgnore
	@ManyToOne
	@JoinColumn(name="parties_id", nullable=false)
	private Party party;
	
	private String accountType;

	public PartyBankDetail() {
	}

	public PartyBankDetail(Long id, BankDetail bankDetails, Party party) {
		this.id = id;
		this.bankDetails = bankDetails;
		this.party = party;
	}

	public PartyBankDetail(Long id, BankDetail bankDetails, Party party,
			String accountType) {
		this.id = id;
		this.bankDetails = bankDetails;
		this.party = party;
		this.accountType = accountType;
	}

	@Override
	public EntityType getModelType()
	{
		return EntityType.PARTY_BANK_DETAIL;
	}
	
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public BankDetail getBankDetails() {
		return this.bankDetails;
	}

	public void setBankDetails(BankDetail bankDetails) {
		this.bankDetails = bankDetails;
	}

	public Party getParty() {
		return this.party;
	}

	public void setParty(Party party) {
		this.party = party;
	}

	public String getAccountType() {
		return this.accountType;
	}

	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}

	@Override
	public int compareTo(PartyBankDetail arg0) {
		return 1;
	}
}
