package com.xioq.dasacumen.model.common;

// Generated 06-May-2014 10:03:55 by Hibernate Tools 4.0.0

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;

import com.xioq.dasacumen.lib.model.VersionControlled;
import com.xioq.dasacumen.model.constants.EntityType;

/**
 * PartyTelephoneNumbers generated by hbm2java
 */
@Entity @Proxy(lazy=false)
@Table(name="party_telephone_numbers")
public class PartyTelephoneNumber extends VersionControlled implements java.io.Serializable, Comparable<PartyTelephoneNumber> {

	@Id @SequenceGenerator(allocationSize=1, sequenceName="party_telephone_numbers_id_seq", name="party_telephone_numbers_id_seq")
	@GeneratedValue(generator="party_telephone_numbers_id_seq", strategy=GenerationType.SEQUENCE)
	private Long id;
	
	@ManyToOne(cascade =CascadeType.ALL)
	@JoinColumn(name="tel_numbers_id", nullable=false)
	private TelephoneNumber telephoneNumber;
	
	@ManyToOne
	@JoinColumn(name="parties_id", nullable=false)
	private Party party;
	
	@Column(name="tel_numbers_type")
	private Long telNumberType;

	public PartyTelephoneNumber() {
	}

	public PartyTelephoneNumber(Long id, TelephoneNumber telephoneNumber, Party party) {
		this.id = id;
		this.telephoneNumber = telephoneNumber;
		this.party = party;
	}

	public PartyTelephoneNumber(Long id, TelephoneNumber telephoneNumber,
			Party party, Long telNumberType) {
		this.id = id;
		this.telephoneNumber = telephoneNumber;
		this.party = party;
		this.telNumberType = telNumberType;
	}

	@Override
	public EntityType getModelType()
	{
		return EntityType.PARTY_TELEPHONE_NUMBER;
	}
	
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public TelephoneNumber getTelephoneNumber() {
		return this.telephoneNumber;
	}

	public void setTelephoneNumber(TelephoneNumber telephoneNumber) {
		this.telephoneNumber = telephoneNumber;
	}

	public Party getParty() {
		return this.party;
	}

	public void setParty(Party party) {
		this.party = party;
	}

	public Long getTelNumberType() {
		return this.telNumberType;
	}

	public void setTelNumberType(Long telNumbersType) {
		this.telNumberType = telNumbersType;
	}

	@Override
	public int compareTo(PartyTelephoneNumber o) {
		// TODO Auto-generated method stub
		return 1;
	}
}
