package com.xioq.dasacumen.model.common;

// Generated 24-Jun-2014 12:24:54 by Hibernate Tools 4.0.0

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;

import com.xioq.dasacumen.lib.model.VersionControlled;
import com.xioq.dasacumen.model.constants.EntityType;

/**
 * PartyContactDetails generated by hbm2java
 */
@Entity @Proxy(lazy=false)
@Table(name="party_contact_details")
public class PartyContactDetail extends VersionControlled implements java.io.Serializable, Comparable<PartyContactDetail> {

	@Id
	@SequenceGenerator(allocationSize=1, sequenceName="party_contact_details_id_seq", name="party_contact_details_id_seq")
	@GeneratedValue(generator="party_contact_details_id_seq", strategy=GenerationType.SEQUENCE)
	private Long id;
	
	@OneToOne(cascade =CascadeType.ALL)
	@JoinColumn(name="party_telephone_numbers_id")
	private PartyTelephoneNumber partyTelephoneNumber;
	
	@OneToOne(cascade =CascadeType.ALL)
	@JoinColumn(name="party_emails_id")
	private PartyEmail partyEmail;
	
	@OneToOne(cascade =CascadeType.ALL)
	@JoinColumn(name="party_addresses_id")
	private PartyAddress partyAddress;
	
	@OneToOne()
	@JoinColumn(name="parties_id", nullable=false)
	private Party party;

	public PartyContactDetail() {
	}

	public PartyContactDetail(Long id,
			PartyTelephoneNumber partyTelephoneNumber,
			PartyEmail partyEmail, PartyAddress partyAddress,
			Party party) {
		this.id = id;
		this.partyTelephoneNumber = partyTelephoneNumber;
		this.partyEmail = partyEmail;
		this.partyAddress = partyAddress;
		this.party = party;
	}

	@Override
	public EntityType getModelType()
	{
		return EntityType.PARTY_CONTACT_DETAIL;
	}
	
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public PartyTelephoneNumber getPartyTelephoneNumber() {
		return this.partyTelephoneNumber;
	}

	public void setPartyTelephoneNumber(
			PartyTelephoneNumber partyTelephoneNumber) {
		this.partyTelephoneNumber = partyTelephoneNumber;
	}

	public PartyEmail getPartyEmail() {
		return this.partyEmail;
	}

	public void setPartyEmail(PartyEmail partyEmail) {
		this.partyEmail = partyEmail;
	}

	public PartyAddress getPartyAddress() {
		return this.partyAddress;
	}

	public void setPartyAddress(PartyAddress partyAddress) {
		this.partyAddress = partyAddress;
	}

	public Party getParty() {
		return this.party;
	}

	public void setParty(Party party) {
		this.party = party;
	}

	@Override
	public int compareTo(PartyContactDetail o) {
		// TODO Auto-generated method stub
		return 0;
	}
}
