package com.xioq.dasacumen.model.common;

// Generated 06-May-2014 10:03:55 by Hibernate Tools 4.0.0

import java.util.Set;
import java.util.SortedSet;
import java.util.TreeSet;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;

import com.xioq.dasacumen.lib.model.VersionControlled;
import com.xioq.dasacumen.model.constants.EntityType;

/**
 * TelNumbers generated by hbm2java
 */
@Entity @Proxy(lazy=false)
@Table(name="tel_numbers")
public class TelephoneNumber extends VersionControlled implements java.io.Serializable {

	@Id
	@SequenceGenerator(allocationSize=1, sequenceName="tel_numbers_id_seq", name="tel_numbers_id_seq")
	@GeneratedValue(generator="tel_numbers_id_seq", strategy=GenerationType.SEQUENCE)
	
	private Long id;

	private String telNo;

	@OneToMany(mappedBy="telephoneNumber", cascade=CascadeType.ALL,  fetch=FetchType.EAGER)
	@OrderBy
	private SortedSet<PartyTelephoneNumber> partyTelephoneNumbers = new TreeSet<PartyTelephoneNumber>();

	public TelephoneNumber() {
	}

	public TelephoneNumber(Long id) {
		this.id = id;
	}

	public TelephoneNumber(Long id, String telNo,
			SortedSet<PartyTelephoneNumber> partyTelephoneNumbers) {
		this.id = id;
		this.telNo = telNo;
		this.partyTelephoneNumbers = partyTelephoneNumbers;
	}

	@Override
	public EntityType getModelType()
	{
		return EntityType.TELEPHONE_NUMBER;
	}
	
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getTelNo() {
		return this.telNo;
	}

	public void setTelNo(String telNo) {
		this.telNo = telNo;
	}

	public Set<PartyTelephoneNumber> getPartyTelephoneNumbers() {
		return this.partyTelephoneNumbers;
	}

	public void setPartyTelephoneNumbers(
			SortedSet<PartyTelephoneNumber> partyTelephoneNumbers) {
		this.partyTelephoneNumbers = partyTelephoneNumbers;
	}

}
