package com.xioq.dasacumen.model.common;

// Generated 06-May-2014 10:03:55 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;

import com.xioq.dasacumen.lib.model.VersionControlled;
import com.xioq.dasacumen.model.assetregister.Assets;
import com.xioq.dasacumen.model.constants.EntityType;
import com.xioq.dasacumen.model.systemadmin.UserData;
import com.xioq.dasacumen.model.systemadmin.UserDataTypes;

/**
 * UserDataSets generated by hbm2java
 */
@Entity
@Proxy(lazy=false)
@Table(name = "user_data_sets")
public class UserDataSets extends VersionControlled implements java.io.Serializable {

	@Id
	@SequenceGenerator(allocationSize=1, initialValue=0, sequenceName="user_data_sets_id_seq", name="user_data_sets_id_seq")
	@GeneratedValue(generator="user_data_sets_id_seq", strategy=GenerationType.SEQUENCE)
	@Column(name="id")
	private Long id;
	
	@ManyToOne()
	@JoinColumn(name="user_data_id", updatable = false, nullable = false)
	private UserData userData;
	
	@ManyToOne()
	@JoinColumn(name="assets_id", updatable = false, nullable = false)
	private Assets assets;

	@ManyToOne()
	@JoinColumn(name="user_data_type_id", updatable = false, nullable = false)
	private UserDataTypes userDataType;
	
	public UserDataSets() {
	}

	public UserDataSets(UserData userData, Assets assets, UserDataTypes userDataType) {
		this.userData = userData;
		this.assets = assets;
		this.userDataType = userDataType;
	}

	public UserDataSets(Long id, UserData userData, Assets assets,
			UserDataTypes userDataType, Integer tenantId, String createdBy,
			Date createdDate, String lastUpdatedBy, Date lastUpdatedDate,
			Integer versionNumber) {
		this.id = id;
		this.userData = userData;
		this.assets = assets;
		this.userDataType = userDataType;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public UserData getUserData() {
		return this.userData;
	}

	public void setUserData(UserData userData) {
		this.userData = userData;
	}

	public Assets getAssets() {
		return this.assets;
	}

	public void setAssets(Assets assets) {
		this.assets = assets;
	}

	public UserDataTypes getUserDataType()
	{
		return userDataType;
	}

	public void setUserDataType(UserDataTypes userDataType)
	{
		this.userDataType = userDataType;
	}

	@Override
	public EntityType getModelType()
	{
		// TODO Auto-generated method stub
		return null;
	}

}
