package com.xioq.dasacumen.model.assetregister;

// Generated 24-Jun-2014 12:24:54 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.hibernate.annotations.Proxy;

import com.xioq.dasacumen.lib.model.VersionControlled;
import com.xioq.dasacumen.model.constants.EntityType;

/**
 * AssetSchedule generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Proxy(lazy=false)
@Table(name="asset_schedule")
public class AssetSchedule extends VersionControlled implements java.io.Serializable {

	@Id 
	@SequenceGenerator(allocationSize=1, initialValue=0, sequenceName="asset_schedule_id_seq", name="asset_schedule_id_seq")
	@GeneratedValue(generator="asset_schedule_id_seq", strategy=GenerationType.SEQUENCE)
	private Long id;
	
	@Column(name="lease_commences", nullable=true)
	private Date leaseCommences;
	
	@Column(name="lease_expires", nullable=true)
	private Date leaseExpires;
	
	@Column(name="date_collected_deployed", nullable=true)
	private Date dateCollectedDeployed;
	
	@JsonIgnore 
	@ManyToOne
	@JoinColumn(name="asset_id", nullable=false)
	private Assets asset;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Date getLeaseCommences() {
		return leaseCommences;
	}

	public void setLeaseCommences(Date leaseCommences) {
		this.leaseCommences = leaseCommences;
	}

	public Date getLeaseExpires() {
		return leaseExpires;
	}

	public void setLeaseExpires(Date leaseExpires) {
		this.leaseExpires = leaseExpires;
	}

	public Assets getAsset() {
		return asset;
	}

	public void setAssets(Assets asset) {
		this.asset = asset;
	}
	
	
	
	public void setDateCollectedDeployed(Date dateCollectedDeployed){
		this.dateCollectedDeployed = dateCollectedDeployed;
	}
	
	public Date getDateCollectedDeployed(){
		return dateCollectedDeployed;
	}

	@Override
	public EntityType getModelType()
	{
		return EntityType.ASSET_SCHEDULE;
	}

}
