package com.xioq.dasacumen.model.assetregister;

// Generated 24-Jun-2014 12:24:54 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;

import com.xioq.dasacumen.lib.model.VersionControlled;
import com.xioq.dasacumen.model.common.LeaseOutExtras;
import com.xioq.dasacumen.model.constants.EntityType;

/**
 * AssetSchedule generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Proxy(lazy=false)
@Table(name="asset_proposal_extras")
public class AssetProposalExtras extends VersionControlled implements java.io.Serializable {

	@Id 
	@SequenceGenerator(allocationSize=1, initialValue=0, sequenceName="asset_proposal_extras_id_seq", name="asset_proposal_extras_id_seq")
	@GeneratedValue(generator="asset_proposal_extras_id_seq", strategy=GenerationType.SEQUENCE)
	private Long id;
	
//	@OneToOne(optional=false)
//	@JoinColumn(name="asset_id", nullable=false)  //nullable=false, updatable=false, insertable=false
//	private Assets asset;
	
	@Column(name="asset_id") // May need to rename
	private Long assetId; // XXX need to add to jira, Jira number .... 
	@OneToOne(optional=false)
    @JoinColumn(name="asset_id",updatable = false, insertable=false)
	private Assets asset;


	@ManyToOne(cascade = {CascadeType.ALL})
	@JoinColumn(name="proposal_id")
	private AssetProposal assetProposal;
	
	@Column(name="lease_out_extras_id")
	private Long leaseOutExtraId; 
	@OneToOne(optional=false)
    @JoinColumn(name="lease_out_extras_id",updatable = false, insertable=false)
	private LeaseOutExtras leaseOutExtras;
	
	@Column(name="cost", precision=131089, scale=0)
	private BigDecimal costOfExtras;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}


	public Long getAssetId() {
		return assetId;
	}

	public void setAssetId(Long assetId) {
		this.assetId = assetId;
	}

	public Assets getAsset() {
		return asset;
	}

	public void setAsset(Assets asset) {
		this.asset = asset;
	}

	public AssetProposal getAssetProposal() {
		return assetProposal;
	}

	public void setAssetProposal(AssetProposal assetProposal) {
		this.assetProposal = assetProposal;
	}


//	public Long getProposalId() {
//		return proposalId;
//	}
//
//	public void setProposalId(Long proposalId) {
//		this.proposalId = proposalId;
//	}

	public BigDecimal getCostOfExtras() {
		return costOfExtras;
	}

	public void setCostOfExtras(BigDecimal costOfExtras) {
		this.costOfExtras = costOfExtras;
	}
	
	public Long getLeaseOutExtraId() {
		return leaseOutExtraId;
	}

	public void setLeaseOutExtraId(Long leaseOutExtraId) {
		this.leaseOutExtraId = leaseOutExtraId;
	}

	public LeaseOutExtras getLeaseOutExtras() {
		return leaseOutExtras;
	}

	public void setLeaseOutExtras(LeaseOutExtras leaseOutExtras) {
		this.leaseOutExtras = leaseOutExtras;
	}

	@Override
	public EntityType getModelType()
	{
		return EntityType.ASSET_PROPOSAL_EXTRAS;
	}
	
}
