package com.xioq.dasacumen.model.assetregister;

// Generated 06-May-2014 10:03:55 by Hibernate Tools 4.0.0

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;

import com.xioq.dasacumen.lib.model.VersionControlled;
import com.xioq.dasacumen.model.constants.EntityType;

/**
 * AssetParts generated by hbm2java
 */
@Entity
@Proxy(lazy=false)
@Table(name = "asset_parts")
public class AssetParts extends VersionControlled implements java.io.Serializable {
	
	@Id
	@SequenceGenerator(allocationSize=1, initialValue=0, sequenceName="asset_parts_id_seq", name="asset_parts_id_seq")
	@GeneratedValue(generator="asset_parts_id_seq", strategy=GenerationType.SEQUENCE)
	private Long id;
	
	@ManyToOne
	@JoinColumn(name="assets_parent_id", nullable=false, updatable = false)
	private Assets parentAsset;
	
	@ManyToOne
	@JoinColumn(name="assets_child_id", nullable=false)
	private Assets childAsset;

	public AssetParts() {
	}

	public AssetParts(long id, Assets assetsByAssetsParentId,
			Assets assetsByAssetsChildId) {
		this.id = id;
		this.parentAsset = assetsByAssetsParentId;
		this.childAsset = assetsByAssetsChildId;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Assets getParentAsset() {
		return this.parentAsset;
	}

	public void setParentAsset(Assets parentAsset) {
		this.parentAsset = parentAsset;
	}

	public Assets getChildAsset() {
		return this.childAsset;
	}

	public void setChildAsset(Assets childAsset) {
		this.childAsset = childAsset;
	}

	@Override
	public EntityType getModelType() {
		return EntityType.ASSET_PARTS;
	}

}
