package com.xioq.dasacumen.model.assetregister;

// Generated 24-Jun-2014 12:24:54 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import java.util.SortedSet;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.hibernate.annotations.Proxy;

import com.xioq.dasacumen.lib.model.VersionControlled;
import com.xioq.dasacumen.model.common.Address;
import com.xioq.dasacumen.model.common.Company;
import com.xioq.dasacumen.model.common.Email;
import com.xioq.dasacumen.model.common.Party;
import com.xioq.dasacumen.model.common.TelephoneNumber;
import com.xioq.dasacumen.model.constants.EntityType;
import com.xioq.dasacumen.model.systemadmin.UserData;

/**
 * AssetSchedule generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Proxy(lazy=false)
@Table(name="asset_proposal")
public class AssetProposal extends VersionControlled implements java.io.Serializable {

	@Id 
	@SequenceGenerator(allocationSize=1, initialValue=0, sequenceName="asset_proposal_id_seq", name="asset_proposal_id_seq")
	@GeneratedValue(generator="asset_proposal_id_seq", strategy=GenerationType.SEQUENCE)
	private Long id;
	
	@JsonIgnore 
	@ManyToOne
	@JoinColumn(name="asset_id")
	private Assets asset;
	
	@JoinColumn(name="asset_schedule_id")
	@OneToOne(cascade = {CascadeType.ALL})
	private AssetSchedule assetSchedule;
	
	//Add below once the proposal extras object exists.
	@OneToMany(mappedBy = "assetProposal", orphanRemoval=true, cascade={CascadeType.ALL}, fetch=FetchType.EAGER)
	private Set<AssetProposalExtras> assetProposalExtras = new HashSet<AssetProposalExtras>(0);
	
	//@TODO XXX : Possibly change address,tel,email etc to just use party contact details?
	
	@OneToOne(cascade={CascadeType.ALL})
	@JoinColumn(name="address_id")
	private Address address;
	
	@OneToOne(cascade={CascadeType.ALL})
	@JoinColumn(name="email_id")
	private Email email;
	
	@OneToOne(cascade={CascadeType.ALL})
	@JoinColumn(name="telephone_id")
	private TelephoneNumber telephone;
	
	@OneToOne(optional=false)
	@JoinColumn(name="client_party_id")
	private Company company;
	
	@OneToOne(optional=false)
	@JoinColumn(name="contact_party_id")
	private Party contactParty;

	//May need to be moved to different file
	@Column(name="invoicing_schedule")
	private Long invoicingScheduleId; 
	@ManyToOne()
    @JoinColumn(name="invoicing_schedule",updatable = false, insertable=false)
	private UserData invoicingSchedule;
	
	@Column(name="charge_period") 
	private Long chargePeriodId; 
	@ManyToOne()
    @JoinColumn(name="charge_period",updatable = false, insertable=false)
	private UserData chargePeriod;
	
	@Column(name="current_status")
	private String currentStatus;
	
	@Column(name="standard_cost", precision=131089, scale=0)
	private BigDecimal standardCost;
	
	@Column(name="periodic_cost", precision=131089, scale=0)
	private BigDecimal periodicCost;

	@Column(name="total_cost", precision=131089, scale=0)
	private BigDecimal totalProposedCost;
	
	@Column(name="decline_comment")
	private String declineComment;
	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}

	public AssetSchedule getAssetSchedule() {
		return assetSchedule;
	}
	public Assets getAsset() {
		return asset;
	}
	
	public void setAsset(Assets asset) {
		this.asset = asset;
	}
	public void setAssetSchedule(AssetSchedule assetSchedule) {
		this.assetSchedule = assetSchedule;
	}

	public Address getAddress() {
		return address;
	}
	public void setAddress(Address address) {
		this.address = address;
	}

	public Email getEmail() {
		return email;
	}
	public void setEmail(Email email) {
		this.email = email;
	}

	public TelephoneNumber getTelephone() {
		return telephone;
	}
	public void setTelephone(TelephoneNumber telephone) {
		this.telephone = telephone;
	}
	
	public Company getCompany()
	{
		return company;
	}
	public void setCompany(Company company)
	{
		this.company = company;
	}
	public Party getContactParty()
	{
		return contactParty;
	}
	public void setContactParty(Party contactParty)
	{
		this.contactParty = contactParty;
	}
	public String getCurrentStatus() {
		return currentStatus;
	}

	public void setCurrentStatus(String currentStatus) {
		this.currentStatus = currentStatus;
	}

	public Set<AssetProposalExtras> getAssetProposalExtras() {
		return assetProposalExtras;
	}
	public void setAssetProposalExtras(Set<AssetProposalExtras> assetProposalExtras) {
		this.assetProposalExtras = assetProposalExtras;
	}
	
	public UserData getInvoicingSchedule() {
		return this.invoicingSchedule;
	}

	public void setInvoicingSchedule(UserData invoicingSchedule) {
		this.invoicingSchedule = invoicingSchedule;
	}

	public Long getInvoicingScheduleId() {
		return invoicingScheduleId;
	}

	public void setInvoicingScheduleId(Long invoicingScheduleId) {
		this.invoicingScheduleId = invoicingScheduleId;
	}
	
	public void setAssetProposalExtras(SortedSet<AssetProposalExtras> assetProposalExtras)
	{
		this.assetProposalExtras = assetProposalExtras;
	}
	
	public void addAssetProposalExtra(AssetProposalExtras assetProposalExtra)
	{
		assetProposalExtra.setAssetProposal(this);
		this.assetProposalExtras.add(assetProposalExtra);
	}
	
	public void removeAssetProposalExtra(AssetProposalExtras assetProposalExtra)
	{
		assetProposalExtra.setAssetProposal(this);
		this.assetProposalExtras.remove(assetProposalExtra);
	}
	
	public void setDeclineComment(String declineComment){
		this.declineComment = declineComment;
	}
	
	public String getDeclineComment(){
		return declineComment;
	}


	@JsonIgnore
	public AssetProposalExtras getAssetProposalExtra()
	{
		if(null == this.assetProposalExtras)
			return null;

		for (AssetProposalExtras aAssetProposalExtra : this.assetProposalExtras)
		{
			if(true)
			{
				return aAssetProposalExtra;
			}
		}
		return null;
	}
	
	private UserData getChargePeriod() 
	{
		return chargePeriod;
	}

	private void setChargePeriod(UserData chargePeriod) 
	{
		this.chargePeriod = chargePeriod;
	}

	public Long getChargePeriodId() 
	{
		return chargePeriodId;
	}

	public void setChargePeriodId(Long chargePeriodId) 
	{
		this.chargePeriodId = chargePeriodId;
	}
	
	public BigDecimal getStandardCost() 
	{
		return standardCost;
	}
	public void setStandardCost(BigDecimal standardCost) 
	{
		this.standardCost = standardCost;
	}
	
	public BigDecimal getPeriodicCost() 
	{
		return periodicCost;
	}
	public void setPeriodicCost(BigDecimal periodicCost) 
	{
		this.periodicCost = periodicCost;
	}
	
	public BigDecimal getTotalProposedCost() 
	{
		return totalProposedCost;
	}
	public void setTotalProposedCost(BigDecimal totalProposedCost) 
	{
		this.totalProposedCost = totalProposedCost;
	}
	
	@Override
	public EntityType getModelType()
	{
		return EntityType.ASSET_PROPOSAL;
	}
}
